name: Test Suite
run-name: Running Test Suite
on: [push]
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Install test dependencies
        run: pip install pytest
      - name: Running pytest tests
        run: pytest tests